/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kb2fty7.testapplication.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserNote service. Represents a row in the &quot;test_portlet_UserNote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kb2fty7.testapplication.model.impl.UserNoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kb2fty7.testapplication.model.impl.UserNoteImpl}.
 * </p>
 *
 * @author Р®СЂРёР№
 * @see UserNote
 * @see com.kb2fty7.testapplication.model.impl.UserNoteImpl
 * @see com.kb2fty7.testapplication.model.impl.UserNoteModelImpl
 * @generated
 */
public interface UserNoteModel extends BaseModel<UserNote> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user note model instance should use the {@link UserNote} interface instead.
	 */

	/**
	 * Returns the primary key of this user note.
	 *
	 * @return the primary key of this user note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user note.
	 *
	 * @param primaryKey the primary key of this user note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this user note.
	 *
	 * @return the ID of this user note
	 */
	public long getId();

	/**
	 * Sets the ID of this user note.
	 *
	 * @param id the ID of this user note
	 */
	public void setId(long id);

	/**
	 * Returns the name of this user note.
	 *
	 * @return the name of this user note
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user note.
	 *
	 * @param name the name of this user note
	 */
	public void setName(String name);

	/**
	 * Returns the lastname of this user note.
	 *
	 * @return the lastname of this user note
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this user note.
	 *
	 * @param lastname the lastname of this user note
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the email of this user note.
	 *
	 * @return the email of this user note
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user note.
	 *
	 * @param email the email of this user note
	 */
	public void setEmail(String email);

	/**
	 * Returns the question of this user note.
	 *
	 * @return the question of this user note
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this user note.
	 *
	 * @param question the question of this user note
	 */
	public void setQuestion(String question);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserNote userNote);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserNote> toCacheModel();

	@Override
	public UserNote toEscapedModel();

	@Override
	public UserNote toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}